let
    Source = Json.Document(File.Contents("C:\Users\berna\Google Drive\Power BI\Default Theme\DefaultTheme.json")),
    #"Converted to Table" = Table.FromRecords({Source}),
    #"Expanded visualStyles" = Table.ExpandRecordColumn(#"Converted to Table", "visualStyles", {"page", "*"}, {"visualStyles.page", "visualStyles.*"}),
    #"Expanded visualStyles.page" = Table.ExpandRecordColumn(#"Expanded visualStyles", "visualStyles.page", {"*"}, {"visualStyles.page.*"}),
    #"Expanded visualStyles.page.*" = Table.ExpandRecordColumn(#"Expanded visualStyles.page", "visualStyles.page.*", {"outspace", "background"}, {"visualStyles.page.*.outspace", "visualStyles.page.*.background"}),
    #"Expanded visualStyles.*" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*", "visualStyles.*", {"*"}, {"visualStyles.*.*"}),
    #"Expanded visualStyles.*.*" = Table.ExpandRecordColumn(#"Expanded visualStyles.*", "visualStyles.*.*", {"background", "visualHeader", "visualTooltip"}, {"visualStyles.*.*.background", "visualStyles.*.*.visualHeader", "visualStyles.*.*.visualTooltip"}),
    #"Expanded textClasses" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*", "textClasses", {"label", "callout", "title", "header"}, {"textClasses.label", "textClasses.callout", "textClasses.title", "textClasses.header"}),
    #"Expanded textClasses.label" = Table.ExpandRecordColumn(#"Expanded textClasses", "textClasses.label", {"color"}, {"textClasses.label.color"}),
    #"Expanded textClasses.callout" = Table.ExpandRecordColumn(#"Expanded textClasses.label", "textClasses.callout", {"color"}, {"textClasses.callout.color"}),
    #"Expanded textClasses.title" = Table.ExpandRecordColumn(#"Expanded textClasses.callout", "textClasses.title", {"color"}, {"textClasses.title.color"}),
    #"Expanded textClasses.header" = Table.ExpandRecordColumn(#"Expanded textClasses.title", "textClasses.header", {"color"}, {"textClasses.header.color"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded textClasses.header",{{"name", type text}, {"dataColors", type any}, {"bad", type text}, {"good", type text}, {"neutral", type text}, {"visualStyles.page.*.outspace", type any}, {"visualStyles.page.*.background", type any}, {"visualStyles.*.*.background", type any}, {"visualStyles.*.*.visualHeader", type any}, {"visualStyles.*.*.visualTooltip", type any}, {"textClasses.label.color", type text}, {"textClasses.callout.color", type text}, {"textClasses.title.color", type text}, {"textClasses.header.color", type text}}),
    #"Extracted Values" = Table.TransformColumns(#"Changed Type", {"dataColors", each Text.Combine(List.Transform(_, Text.From), ","), type text}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Extracted Values", "dataColors", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"dataColors.1", "dataColors.2", "dataColors.3", "dataColors.4", "dataColors.5", "dataColors.6", "dataColors.7", "dataColors.8"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"dataColors.1", type text}, {"dataColors.2", type text}, {"dataColors.3", type text}, {"dataColors.4", type text}, {"dataColors.5", type text}, {"dataColors.6", type text}, {"dataColors.7", type text}, {"dataColors.8", type text}}),
    #"Expanded visualStyles.page.*.outspace" = Table.ExpandListColumn(#"Changed Type1", "visualStyles.page.*.outspace"),
    #"Expanded visualStyles.page.*.outspace1" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.outspace", "visualStyles.page.*.outspace", {"color"}, {"visualStyles.page.*.outspace.color"}),
    #"Expanded visualStyles.page.*.outspace.color" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.outspace1", "visualStyles.page.*.outspace.color", {"solid"}, {"visualStyles.page.*.outspace.color.solid"}),
    #"Expanded visualStyles.page.*.outspace.color.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.outspace.color", "visualStyles.page.*.outspace.color.solid", {"color"}, {"visualStyles.page.*.outspace.color.solid.color"}),
    #"Expanded visualStyles.page.*.background" = Table.ExpandListColumn(#"Expanded visualStyles.page.*.outspace.color.solid", "visualStyles.page.*.background"),
    #"Expanded visualStyles.page.*.background1" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.background", "visualStyles.page.*.background", {"color"}, {"visualStyles.page.*.background.color"}),
    #"Expanded visualStyles.page.*.background.color" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.background1", "visualStyles.page.*.background.color", {"solid"}, {"visualStyles.page.*.background.color.solid"}),
    #"Expanded visualStyles.page.*.background.color.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.page.*.background.color", "visualStyles.page.*.background.color.solid", {"color"}, {"visualStyles.page.*.background.color.solid.color"}),
    #"Expanded visualStyles.*.*.background" = Table.ExpandListColumn(#"Expanded visualStyles.page.*.background.color.solid", "visualStyles.*.*.background"),
    #"Expanded visualStyles.*.*.background1" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.background", "visualStyles.*.*.background", {"color"}, {"visualStyles.*.*.background.color"}),
    #"Expanded visualStyles.*.*.background.color" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.background1", "visualStyles.*.*.background.color", {"solid"}, {"visualStyles.*.*.background.color.solid"}),
    #"Expanded visualStyles.*.*.background.color.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.background.color", "visualStyles.*.*.background.color.solid", {"color"}, {"visualStyles.*.*.background.color.solid.color"}),
    #"Expanded visualStyles.*.*.visualHeader" = Table.ExpandListColumn(#"Expanded visualStyles.*.*.background.color.solid", "visualStyles.*.*.visualHeader"),
    #"Expanded visualStyles.*.*.visualHeader1" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualHeader", "visualStyles.*.*.visualHeader", {"background"}, {"visualStyles.*.*.visualHeader.background"}),
    #"Expanded visualStyles.*.*.visualHeader.background" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualHeader1", "visualStyles.*.*.visualHeader.background", {"solid"}, {"visualStyles.*.*.visualHeader.background.solid"}),
    #"Expanded visualStyles.*.*.visualHeader.background.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualHeader.background", "visualStyles.*.*.visualHeader.background.solid", {"color"}, {"visualStyles.*.*.visualHeader.background.solid.color"}),
    #"Expanded visualStyles.*.*.visualTooltip" = Table.ExpandListColumn(#"Expanded visualStyles.*.*.visualHeader.background.solid", "visualStyles.*.*.visualTooltip"),
    #"Expanded visualStyles.*.*.visualTooltip1" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualTooltip", "visualStyles.*.*.visualTooltip", {"titleFontColor", "valueFontColor"}, {"visualStyles.*.*.visualTooltip.titleFontColor", "visualStyles.*.*.visualTooltip.valueFontColor"}),
    #"Expanded visualStyles.*.*.visualTooltip.titleFontColor" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualTooltip1", "visualStyles.*.*.visualTooltip.titleFontColor", {"solid"}, {"visualStyles.*.*.visualTooltip.titleFontColor.solid"}),
    #"Expanded visualStyles.*.*.visualTooltip.titleFontColor.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualTooltip.titleFontColor", "visualStyles.*.*.visualTooltip.titleFontColor.solid", {"color"}, {"visualStyles.*.*.visualTooltip.titleFontColor.solid.color"}),
    #"Expanded visualStyles.*.*.visualTooltip.valueFontColor" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualTooltip.titleFontColor.solid", "visualStyles.*.*.visualTooltip.valueFontColor", {"solid"}, {"visualStyles.*.*.visualTooltip.valueFontColor.solid"}),
    #"Expanded visualStyles.*.*.visualTooltip.valueFontColor.solid" = Table.ExpandRecordColumn(#"Expanded visualStyles.*.*.visualTooltip.valueFontColor", "visualStyles.*.*.visualTooltip.valueFontColor.solid", {"color"}, {"visualStyles.*.*.visualTooltip.valueFontColor.solid.color"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded visualStyles.*.*.visualTooltip.valueFontColor.solid",{"visualStyles.*.*.background.color.solid.color", "visualStyles.*.*.visualHeader.background.solid.color", "visualStyles.*.*.visualTooltip.titleFontColor.solid.color", "visualStyles.*.*.visualTooltip.valueFontColor.solid.color", "textClasses.label.color", "textClasses.callout.color", "textClasses.title.color", "textClasses.header.color"}),
    #"Removed Columns" = Table.RemoveColumns(#"Removed Columns1",{"name"}),
    #"Demoted Headers" = Table.DemoteHeaders(#"Removed Columns"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}}),
    #"Transposed Table" = Table.Transpose(#"Changed Type2"),
    #"Renamed Columns" = Table.RenameColumns(#"Transposed Table",{{"Column1", "Color Name"}, {"Column2", "Color Code"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","visualStyles.page.*.","",Replacer.ReplaceText,{"Color Name"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".color.solid.color","",Replacer.ReplaceText,{"Color Name"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","dataColors.","color ",Replacer.ReplaceText,{"Color Name"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value2",{{"Color Code", type text}})
in
    #"Changed Type3"